name: CI

on:
  push:
    branches:
    - main
    - develop
    - release/*
  pull_request:
    branches: 
    - main
    - develop
    - release/*

  workflow_dispatch:

jobs:
  build-linux:
    name: flutter build linux
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Create empty token file
      run: echo 'const token = "";' > test_app/integration_tests/end_to_end/token.dart
    - name: Set up Java 🔧
      uses: actions/setup-java@v3
      with:
        java-version: 15
        distribution: 'adopt'
    - name: Set up Flutter version 🔧
      uses: ./.github/actions/flutter-action
      with:
        flutter-version: $FLUTTER_VERSION
    - name: Fetch dependencies
      run: |
        flutter pub get
    - name: Run tests
      run: |
        flutter test -r expanded
    - name: Run pana analyzer
      run: |
        ./scripts/score_analyzer.sh
    - name: Build app
      run: |
        ./scripts/build-android.sh
    - name: Analyze
      run: |
        flutter analyze

  build-macos-android:
    name: flutter build macos android
    runs-on: macos-12
    env:
      FLUTTER_VERSION: "3.0.3"
      ANDROID_SDK_ROOT: "/Users/runner/android-sdk"
      ANDROID_HOME: "~/.android"
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 15
        distribution: 'zulu'
    - name: Set up Flutter version 🔧
      uses: ./.github/actions/flutter-action
      with:
        flutter-version: $FLUTTER_VERSION
    - name: Fetch dependencies
      run: |
        flutter pub get
    - name: Set up android enviroment
      run: |
        ./scripts/macos_setup_android_env.sh
    - name: Configure sdkmanager
      run: |
        ./scripts/macos_configure-sdkmanager.sh
    - name: Run android integration tests
      run: |
        ./scripts/run-mocked-integration-tests-android.sh

  build-macos-ios:
    name: flutter build macos ios
    runs-on: macos-12
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Create empty token file
      run: echo 'const token = "";' > test_app/integration_tests/end_to_end/token.dart
    - name: Set up Flutter version 🔧
      uses: ./.github/actions/flutter-action
      with:
        flutter-version: $FLUTTER_VERSION
    - name: Fetch dependencies
      run: |
        flutter pub get
    - name: Update Cocoapods repo
      run: cd test_app/ios && pod repo update
    - name: Run unmocked integration tests
      env: 
        APP_KEY: ${{ secrets.DOLBYIO_APP_KEY }}
        URL: ${{ secrets.DOLBYIO_APP_SDK_USER_ACCESS_TOKEN_URL }}
      run: |
        ./scripts/run-end-to-end-tests-ios.rb "${URL}" "${APP_KEY}"
    - name: Run mocked integration tests
      run: |
        ./scripts/run-mocked-integration-tests-ios.rb
    - name: Analyze
      run: |
        flutter analyze
