name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-doc-linux:
    name: flutter build linux
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.0.3"
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
      - name: Set up Flutter version
        uses: ./.github/actions/flutter-action
        with:
          flutter-version: $FLUTTER_VERSION

      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dart

      - name: Install dependencies
        run: |
         dart pub get
      - name: Generate dart doc
        run: |
         dart doc .  
      - name: Deploy github pages🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          force : true
          single-commit: true
          folder: doc/api # The folder the action should deploy.

